# Generated by Django 4.0.2 on 2022-02-14 07:49

from django.db import migrations, models
import multiprocessing.sharedctypes


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('resume', models.FileField(default=multiprocessing.sharedctypes.Value, upload_to='static/')),
                ('email', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('linkedin', models.CharField(max_length=100)),
                ('github', models.CharField(max_length=100)),
            ],
        ),
    ]
