# Generated by Django 4.0.2 on 2022-02-17 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(help_text='Email Id', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], help_text='male or female', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='github',
            field=models.CharField(help_text='github url', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='linkedin',
            field=models.CharField(help_text='linked in url', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(help_text='Name of Employee', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(help_text='Phone Number', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='resume',
            field=models.FileField(help_text='Resume File', upload_to='static/'),
        ),
    ]
